CC = gcc
CFLAGS = -MMD -Wall -g

main_cp143a: main_cp143a.c
	$(CC) $(CFLAGS) main_cp143a.c -o main_cp143a

# SRC = $(wildcard *.c)
# OBJ = $(SRC.c=.o)

# EXE = $(SRC:.c=)

# all: $(EXE)

# $(EXE): $(OBJ)
# 	$(CC) $@.o -o $@

# %.o: %.c
# 	$(CC) $(CFLAGS) -c $< -o $@
